// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZI26lcBtnm_JAWaKQQtT3KiqfQA0qFgk',
    appId: '1:70793391960:web:b34e894b7689da98007f2d',
    messagingSenderId: '70793391960',
    projectId: 'flutter-final-762d1',
    authDomain: 'flutter-final-762d1.firebaseapp.com',
    storageBucket: 'flutter-final-762d1.firebasestorage.app',
    measurementId: 'G-D2CB0N3WLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1z0iiKTyKzi7kVKi-HvyKuLh9ULXXMG4',
    appId: '1:70793391960:android:d3022aedda1745b5007f2d',
    messagingSenderId: '70793391960',
    projectId: 'flutter-final-762d1',
    storageBucket: 'flutter-final-762d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaeGKQ4KpCzB5e2y81pv15xR0HvuSp4_I',
    appId: '1:70793391960:ios:2b1a891024f86db6007f2d',
    messagingSenderId: '70793391960',
    projectId: 'flutter-final-762d1',
    storageBucket: 'flutter-final-762d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaeGKQ4KpCzB5e2y81pv15xR0HvuSp4_I',
    appId: '1:70793391960:ios:2b1a891024f86db6007f2d',
    messagingSenderId: '70793391960',
    projectId: 'flutter-final-762d1',
    storageBucket: 'flutter-final-762d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZI26lcBtnm_JAWaKQQtT3KiqfQA0qFgk',
    appId: '1:70793391960:web:6e1f0ec3cf72a1a0007f2d',
    messagingSenderId: '70793391960',
    projectId: 'flutter-final-762d1',
    authDomain: 'flutter-final-762d1.firebaseapp.com',
    storageBucket: 'flutter-final-762d1.firebasestorage.app',
    measurementId: 'G-31CQSQXXK6',
  );
}
