class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'HR Management',
      'login_title': 'Login to your account',
      'login_btn': 'LOGIN',
      'register_btn': 'Register',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'home_tab_info': 'My Info',
      'home_tab_salary': 'Salary',
      'home_tab_profile': 'Profile',
      'home_tab_employees': 'Employees',
      'profile_title': 'My Profile',
      'personal_info': 'Personal Information',
      'update_profile': 'Update Profile',
      'security': 'Security',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'logout': 'Logout',
      'employee_list_title': 'Employees',
      'search_placeholder': 'Search employees...',
      'no_employees': 'No employees found',
      'salary_title': 'My Salary',
      'select_year': 'Select Year:',
      'basic_salary': 'Basic Salary',
      'allowance': 'Allowance',
      'bonus': 'Bonus',
      'overtime': 'Overtime',
      'total_gross': 'Total Gross',
      'net_salary': 'Net Salary',
      'status': 'Status',
      'paid': 'Paid',
      'approved': 'Approved',
      'pending': 'Pending',
      'hello': 'Hello',
      'welcome_back': 'Welcome Back',
    },
    'vi': {
      'app_title': 'Quản Lý Nhân Sự',
      'login_title': 'Đăng nhập vào hệ thống',
      'login_btn': 'ĐĂNG NHẬP',
      'register_btn': 'Đăng ký',
      'email': 'Email',
      'password': 'Mật khẩu',
      'forgot_password': 'Quên mật khẩu?',
      'dont_have_account': 'Chưa có tài khoản?',
      'home_tab_info': 'Thông tin',
      'home_tab_salary': 'Lương',
      'home_tab_profile': 'Hồ sơ',
      'home_tab_employees': 'Nhân viên',
      'profile_title': 'Hồ sơ của tôi',
      'personal_info': 'Thông tin cá nhân',
      'update_profile': 'Cập nhật hồ sơ',
      'security': 'Bảo mật',
      'change_password': 'Đổi mật khẩu',
      'current_password': 'Mật khẩu hiện tại',
      'new_password': 'Mật khẩu mới',
      'logout': 'Đăng xuất',
      'employee_list_title': 'Danh sách nhân viên',
      'search_placeholder': 'Tìm kiếm nhân viên...',
      'no_employees': 'Không tìm thấy nhân viên',
      'salary_title': 'Lương của tôi',
      'select_year': 'Chọn năm:',
      'basic_salary': 'Lương cơ bản',
      'allowance': 'Phụ cấp',
      'bonus': 'Thưởng',
      'overtime': 'Làm thêm giờ',
      'total_gross': 'Tổng thu nhập',
      'net_salary': 'Thực lãnh',
      'status': 'Trạng thái',
      'paid': 'Đã thanh toán',
      'approved': 'Đã duyệt',
      'pending': 'Chờ duyệt',
      'hello': 'Xin chào',
      'welcome_back': 'Chào mừng trở lại',
    },
  };

  static String getString(String code, String key) {
    return _localizedValues[code]?[key] ?? key;
  }
}
